force-app/main/default/objects/ATR_Choice__c/ATR_Choice__c.object-meta.xml
<CustomObject>
    <label>ATR Choice</label>
    <nameField>
        <displayFormat>ATR Choice-{0000}</displayFormat>
        <label>ATR Choice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ATR Choices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ATR_Choice__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <label>Answer</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ATR_Choice__c/fields/ATR_Question__c.field-meta.xml
<CustomField>
    <fullName>ATR_Question__c</fullName>
    <label>ATR Question</label>
    <referenceTo>ATR_Question__c</referenceTo>
    <relationshipLabel>ATR Choices</relationshipLabel>
    <relationshipName>ATR_Choices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ATR_Choice__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Order Number</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ATR_Question__c/ATR_Question__c.object-meta.xml
<CustomObject>
    <label>ATR Question</label>
    <nameField>
        <displayFormat>ATR Question-{0000}</displayFormat>
        <label>ATR Questions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ATR Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ATR_Question__c/fields/ATR_Template__c.field-meta.xml
<CustomField>
    <fullName>ATR_Template__c</fullName>
    <label>ATR Template</label>
    <referenceTo>ATR_Template__c</referenceTo>
    <relationshipLabel>ATR Questions</relationshipLabel>
    <relationshipName>ATR_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ATR_Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ATR_Question_Response__c/ATR_Question_Response__c.object-meta.xml
<CustomObject>
    <label>ATR Question Response</label>
    <nameField>
        <displayFormat>ATR QR {000000}</displayFormat>
        <label>ATR Question Response No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ATR Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ATR_Question_Response__c/fields/ATR_Question__c.field-meta.xml
<CustomField>
    <fullName>ATR_Question__c</fullName>
    <label>ATR Question</label>
    <referenceTo>ATR_Question__c</referenceTo>
    <relationshipLabel>ATR Question Responses</relationshipLabel>
    <relationshipName>ATR_Question_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ATR_Question_Response__c/fields/ATR_Taken__c.field-meta.xml
<CustomField>
    <fullName>ATR_Taken__c</fullName>
    <label>ATR Taken</label>
    <referenceTo>ATR_Taken__c</referenceTo>
    <relationshipLabel>ATR Question Responses</relationshipLabel>
    <relationshipName>ATR_Question_Responses</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ATR_Question_Response__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ATR_Question_Response__c/fields/Response_Score__c.field-meta.xml
<CustomField>
    <fullName>Response_Score__c</fullName>
    <label>Response Score</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ATR_Taken__c/ATR_Taken__c.object-meta.xml
<CustomObject>
    <label>ATR Taken</label>
    <nameField>
        <displayFormat>ATR-{00000}</displayFormat>
        <label>ATR Completed No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ATRs Taken</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ATR_Taken__c/fields/ATR_Score__c.field-meta.xml
<CustomField>
    <fullName>ATR_Score__c</fullName>
    <label>ATR Score</label>
    <summarizedField>ATR_Question_Response__c.Response_Score__c</summarizedField>
    <summaryForeignKey>ATR_Question_Response__c.ATR_Taken__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/ATR_Taken__c/fields/ATR_Template__c.field-meta.xml
<CustomField>
    <fullName>ATR_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ATR Template</label>
    <referenceTo>ATR_Template__c</referenceTo>
    <relationshipLabel>ATRs Taken</relationshipLabel>
    <relationshipName>ATRs_Taken</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ATR_Taken__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Risk Profile History</relationshipLabel>
    <relationshipName>ATRs_Taken</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ATR_Template__c/ATR_Template__c.object-meta.xml
<CustomObject>
    <label>ATR Template</label>
    <nameField>
        <label>ATR Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ATR Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ATR_QuestionnaireControllerTest.cls
@isTest
public class ATR_QuestionnaireControllerTest {
    
    @isTest
    static void questionnaireControllerTest() {
        Account client = new Account( Name = 'Andrew Foster' );
        insert client;
        
        ATR_Template__c template = new ATR_Template__c( Name = 'TestTemplate' );
        insert template;
        
        List<ATR_Question__c> questions = new List<ATR_Question__c>();
        Integer numQuestions = 4;
        for (Integer i = 0; i < numQuestions; i++) {
            questions.add(new ATR_Question__c(Question__c = 'Question ' + i,
                                                       Order_Number__c = i,
                                                       ATR_Template__c = template.Id));
        }
        
        insert questions;
        
        List<ATR_Question__c> actualQuestions = ATR_QuestionnaireController.getQuestions(template.Id);
        System.assertEquals(numQuestions, actualQuestions.size());
        for (Integer i = 0; i < numQuestions; i++) {
            System.assertEquals('Question ' + i, actualQuestions[i].Question__c);
        }
        
        List<ATR_Choice__c> choices = new List<ATR_Choice__c>();
        choices.add(new ATR_Choice__c(Answer__c = 'Strongly Agree',    Score__c = 0, ATR_Question__c = actualQuestions[0].Id));
        choices.add(new ATR_Choice__c(Answer__c = 'Strongly Disagree', Score__c = 5, ATR_Question__c = actualQuestions[0].Id));
        choices.add(new ATR_Choice__c(Answer__c = 'Agree',             Score__c = 1, ATR_Question__c = actualQuestions[1].Id));
        choices.add(new ATR_Choice__c(Answer__c = 'Disagree',          Score__c = 4, ATR_Question__c = actualQuestions[1].Id));
        choices.add(new ATR_Choice__c(Answer__c = 'Not sure',          Score__c = 3, ATR_Question__c = actualQuestions[1].Id));
        insert choices;
        
        List<ATR_Choice__c> actualChoices = ATR_QuestionnaireController.getAnswerChoices(actualQuestions[0].Id);
        
        System.assertEquals(2, actualChoices.size());
        actualChoices = ATR_QuestionnaireController.getAnswerChoices(actualQuestions[1].Id);
        System.assertEquals(3, actualChoices.size());
        
        List<ATR_Question_Response__c> responses = new List<ATR_Question_Response__c>();
        responses.add(new ATR_Question_Response__c(ATR_Question__c = actualQuestions[0].Id, Response__c = 'Strongly Agree', Response_Score__c = 0));
        responses.add(new ATR_Question_Response__c(ATR_Question__c = actualQuestions[1].Id, Response__c = 'Disagree', Response_Score__c = 4));
        
        ATR_Taken__c actualATR = ATR_QuestionnaireController.submitAnswers(client.Id, template.Id, responses);
        List<ATR_Question_Response__c> actualReponses = [ SELECT Id FROM ATR_Question_Response__c WHERE ATR_Taken__c = :actualATR.Id ];
        System.assertEquals(2, actualReponses.size());
        System.assertEquals(template.Id, actualATR.ATR_Template__c);
        System.assertEquals(client.Id, actualATR.Client__c);
        System.assertEquals(4, actualATR.ATR_Score__c);
       
    }
}