force-app/main/default/objects/ATR_Choice__c/ATR_Choice__c.object-meta.xml
<CustomObject>
    <label>ATR Choice</label>
    <nameField>
        <displayFormat>ATR Choice-{0000}</displayFormat>
        <label>ATR Choice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ATR Choices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ATR_Choice__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <label>Answer</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ATR_Choice__c/fields/ATR_Question__c.field-meta.xml
<CustomField>
    <fullName>ATR_Question__c</fullName>
    <label>ATR Question</label>
    <referenceTo>ATR_Question__c</referenceTo>
    <relationshipLabel>ATR Choices</relationshipLabel>
    <relationshipName>ATR_Choices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ATR_Choice__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Order Number</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ATR_Question__c/ATR_Question__c.object-meta.xml
<CustomObject>
    <label>ATR Question</label>
    <nameField>
        <displayFormat>ATR Question-{0000}</displayFormat>
        <label>ATR Questions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ATR Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ATR_Question__c/fields/ATR_Template__c.field-meta.xml
<CustomField>
    <fullName>ATR_Template__c</fullName>
    <label>ATR Template</label>
    <referenceTo>ATR_Template__c</referenceTo>
    <relationshipLabel>ATR Questions</relationshipLabel>
    <relationshipName>ATR_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ATR_Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ATR_Question_Response__c/ATR_Question_Response__c.object-meta.xml
<CustomObject>
    <label>ATR Question Response</label>
    <nameField>
        <displayFormat>ATR QR {000000}</displayFormat>
        <label>ATR Question Response No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ATR Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ATR_Question_Response__c/fields/ATR_Question__c.field-meta.xml
<CustomField>
    <fullName>ATR_Question__c</fullName>
    <label>ATR Question</label>
    <referenceTo>ATR_Question__c</referenceTo>
    <relationshipLabel>ATR Question Responses</relationshipLabel>
    <relationshipName>ATR_Question_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ATR_Question_Response__c/fields/ATR_Taken__c.field-meta.xml
<CustomField>
    <fullName>ATR_Taken__c</fullName>
    <label>ATR Taken</label>
    <referenceTo>ATR_Taken__c</referenceTo>
    <relationshipLabel>ATR Question Responses</relationshipLabel>
    <relationshipName>ATR_Question_Responses</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ATR_Taken__c/ATR_Taken__c.object-meta.xml
<CustomObject>
    <label>ATR Taken</label>
    <nameField>
        <displayFormat>ATR-{00000}</displayFormat>
        <label>ATR Completed No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ATRs Taken</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ATR_Taken__c/fields/ATR_Score__c.field-meta.xml
<CustomField>
    <fullName>ATR_Score__c</fullName>
    <label>ATR Score</label>
    <summarizedField>ATR_Question_Response__c.Response_Score__c</summarizedField>
    <summaryForeignKey>ATR_Question_Response__c.ATR_Taken__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/ATR_Taken__c/fields/ATR_Template__c.field-meta.xml
<CustomField>
    <fullName>ATR_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ATR Template</label>
    <referenceTo>ATR_Template__c</referenceTo>
    <relationshipLabel>ATRs Taken</relationshipLabel>
    <relationshipName>ATRs_Taken</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ATR_Taken__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Risk Profile History</relationshipLabel>
    <relationshipName>ATRs_Taken</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ATR_Template__c/ATR_Template__c.object-meta.xml
<CustomObject>
    <label>ATR Template</label>
    <nameField>
        <label>ATR Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ATR Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ATR_QuestionnaireController.cls
public with sharing class ATR_QuestionnaireController {
    @AuraEnabled
    public static List<ATR_Question__c> getQuestions(String templateId) {
        List<ATR_Question__c> questions = new List<ATR_Question__c>();
        
        List<string> fields = new List<string> { 
            'Id', 
            'ATR_Template__c',
            'Question__c'
        };
        
        boolean isAccessible = ATR_FLSCheck.checkFLS(ATR_Question__c.sObjectType.getDescribe(), fields, 'Read');
        if (isAccessible) {
            questions = [ SELECT Id, ATR_Template__c, Question__c
                          FROM ATR_Question__c
                          WHERE ATR_Template__c = :templateId
                          ORDER BY Order_Number__c ];
        }
        return questions;
    }

    @auraEnabled
    public static List<ATR_Choice__c> getAnswerChoices(String questionId) {
        List<ATR_Choice__c> choices = new List<ATR_Choice__c>();
        
        List<string> fields = new List<string> { 
            'Id', 
            'Answer__c',
            'Score__c',
            'Order_Number__c'
        };
        
        boolean isAccessible = ATR_FLSCheck.checkFLS(ATR_Choice__c.sObjectType.getDescribe(), fields, 'Read');
        if (isAccessible) {
            choices = [ SELECT Id, Answer__c, Score__c
                        FROM ATR_Choice__c
                        WHERE ATR_Question__c = :questionId
                        ORDER BY Order_Number__c ];
        }
        return choices;
    }

    @auraEnabled
    public static ATR_Taken__c submitAnswers(String clientId, String templateId, List<ATR_Question_Response__c> responses) {
        ATR_Taken__c taken;
        
        // Create an ATR Taken record to store the questionnaire result
        Boolean isCreateable = ATR_FLSCheck.checkObjectSecurity(ATR_Taken__c.sObjectType.getDescribe(), 'Create');
        if (isCreateable) {
            
            taken = new ATR_Taken__c(Client__c = clientId, ATR_Template__c = templateId);
            insert taken;
            
            // Add responses for the questionnaire
            isCreateable = ATR_FLSCheck.checkObjectSecurity(ATR_Question_Response__c.sObjectType.getDescribe(), 'Create');
            if (isCreateable) {
                for (ATR_Question_Response__c response : responses) {
                    response.ATR_Taken__c = taken.Id;
                }
                insert responses;
                
                // Query the ATR Taken record to get scores
                List<string> fields = new List<string> { 
                    'Id', 
                    'ATR_Template__c',
                    'Client__c',
                    'ATR_Score__c'
                };
                
                boolean isAccessible = ATR_FLSCheck.checkFLS(ATR_Taken__c.sObjectType.getDescribe(), fields, 'Read');
                if (isAccessible) {
                    List<ATR_Taken__c> atrs = [ SELECT Id, ATR_Template__c, Client__c, ATR_Score__c 
                                                         FROM ATR_Taken__c 
                                                         WHERE Id = :taken.Id ];
                    if (atrs.size() > 0) {
                        taken = atrs[0];
                    }
                }
            }
        }
        return taken;
    }
}