force-app/main/default/objects/ATR_Choice__c/ATR_Choice__c.object-meta.xml
<CustomObject>
    <label>ATR Choice</label>
    <nameField>
        <displayFormat>ATR Choice-{0000}</displayFormat>
        <label>ATR Choice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ATR Choices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ATR_Choice__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <label>Answer</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ATR_Choice__c/fields/ATR_Question__c.field-meta.xml
<CustomField>
    <fullName>ATR_Question__c</fullName>
    <label>ATR Question</label>
    <referenceTo>ATR_Question__c</referenceTo>
    <relationshipLabel>ATR Choices</relationshipLabel>
    <relationshipName>ATR_Choices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ATR_Choice__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Order Number</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ATR_Question__c/ATR_Question__c.object-meta.xml
<CustomObject>
    <label>ATR Question</label>
    <nameField>
        <displayFormat>ATR Question-{0000}</displayFormat>
        <label>ATR Questions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ATR Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ATR_Question__c/fields/ATR_Template__c.field-meta.xml
<CustomField>
    <fullName>ATR_Template__c</fullName>
    <label>ATR Template</label>
    <referenceTo>ATR_Template__c</referenceTo>
    <relationshipLabel>ATR Questions</relationshipLabel>
    <relationshipName>ATR_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ATR_Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ATR_Template__c/ATR_Template__c.object-meta.xml
<CustomObject>
    <label>ATR Template</label>
    <nameField>
        <label>ATR Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ATR Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ATR_Template__c/fields/Maximum_Total_Score__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Total_Score__c</fullName>
    <label>Maximum Total Score</label>
    <summarizedField>ATR_Question__c.Maximum_Score__c</summarizedField>
    <summaryForeignKey>ATR_Question__c.ATR_Template__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/ATR_Template__c/fields/Minimum_Total_Score__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Total_Score__c</fullName>
    <label>Minimum Total Score</label>
    <summarizedField>ATR_Question__c.Minimum_Score__c</summarizedField>
    <summaryForeignKey>ATR_Question__c.ATR_Template__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Risk_Profile__c/Risk_Profile__c.object-meta.xml
<CustomObject>
    <label>Risk Profile</label>
    <nameField>
        <label>Risk Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Risk_Profile__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>This is the description text that will display on the summary page after a questionnaire has been taken.</inlineHelpText>
    <label>Description</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Risk_Profile__c/fields/HighScore__c.field-meta.xml
<CustomField>
    <fullName>HighScore__c</fullName>
    <inlineHelpText>If the total score for a client falls between the Low and High Bands for a &apos;Risk Profile&apos; that profile will be selected.  Scores should not overlap, i.e. If the previous profile has a &apos;High Band&apos; of 10, the &apos;Low Band&apos; of this profile should start at 11.</inlineHelpText>
    <label>High Band</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Risk_Profile__c/fields/LowScore__c.field-meta.xml
<CustomField>
    <fullName>LowScore__c</fullName>
    <inlineHelpText>If the total score for a client falls between the Low and High Bands for a &apos;Risk Profile&apos; that profile will be selected.  Scores should not overlap, i.e. If the previous profile has a &apos;High Band&apos; of 10, the &apos;Low Band&apos; of this profile should start at 11.</inlineHelpText>
    <label>Low Band</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ATR_ConfigController.cls
public with sharing class ATR_ConfigController {
    @AuraEnabled
    public static List<ATR_Template__c> getTemplates() {
		List<ATR_Template__c> templates = new List<ATR_Template__c>();
        List<string> fields = new List<string> { 
            'Id', 
            'Name',
            'Maximum_Total_Score__c',
            'Minimum_Total_Score__c'
        };
        boolean isAccessible = ATR_FLSCheck.checkFLS(ATR_Template__c.sObjectType.getDescribe(), fields, 'Read');
        if (isAccessible) {
            templates = [ SELECT Id, Name, Maximum_Total_Score__c, Minimum_Total_Score__c 
                          FROM ATR_Template__c 
                          ORDER BY Name ];
        }
        return templates;
    }
    
    @AuraEnabled
    public static ATR_Template__c getTemplate(String templateId) {
		ATR_Template__c template = new ATR_Template__c();
        List<string> fields = new List<string> { 
            'Id', 
            'Name',
            'Maximum_Total_Score__c',
            'Minimum_Total_Score__c'
        };
        boolean isAccessible = ATR_FLSCheck.checkFLS(ATR_Template__c.sObjectType.getDescribe(), fields, 'Read');
        if (isAccessible) {
            template = [ SELECT Id, Name, Maximum_Total_Score__c, Minimum_Total_Score__c 
                         FROM ATR_Template__c
                         WHERE Id = :templateId];
        }
        return template;
    }
    
    @AuraEnabled
    public static ATR_Template__c addTemplate(String templateName) {
        ATR_Template__c template;
        Boolean isCreateable = ATR_FLSCheck.checkObjectSecurity(ATR_Template__c.sObjectType.getDescribe(), 'Create');
        if (isCreateable) {
            template = new ATR_Template__c( Name = templateName );
        	insert template;
            template = getTemplate(template.Id);
        }
        return template;
    }
        
    @AuraEnabled
    public static List<ATR_Question__c> getTemplateQuestions(String templateId) {
        List<ATR_Question__c> questions = new List<ATR_Question__c>();
        List<string> fields = new List<string> { 
            'Id',
            'Question__c',
            'Order_Number__c'
        };
        boolean isAccessible = ATR_FLSCheck.checkFLS(ATR_Question__c.sObjectType.getDescribe(), fields, 'Read');
        if (isAccessible) {
            questions = [ SELECT Id, Question__c, Order_Number__c
                          FROM ATR_Question__c 
                          WHERE ATR_Template__c =: templateId
                          ORDER BY Order_Number__c ];
        }
        return questions;
    }
    
    @AuraEnabled
    public static List<Risk_Profile__c> getProfiles() {
        List<Risk_Profile__c> profiles = new List<Risk_Profile__c>();
        List<string> fields = new List<string> { 
            'Id', 
            'Name',
            'Description__c',
            'HighScore__c',
            'LowScore__c'
        };
        boolean isAccessible = ATR_FLSCheck.checkFLS(Risk_Profile__c.sObjectType.getDescribe(), fields, 'Read');
        if (isAccessible) {
            profiles = [ SELECT Id, Name, Description__c, HighScore__c, LowScore__c
                         FROM Risk_Profile__c 
                         ORDER BY LowScore__c ];
        }
        return profiles;
    }

    @AuraEnabled
    public static List<ATR_Question__c> updateQuestion(ATR_Question__c question,
                                                                List<ATR_Choice__c> answers,
                                                                List<ATR_Choice__c> todelete,
                                                                String templateId) { 
                                                           
        boolean isUpsertable = ATR_FLSCheck.checkObjectSecurity(ATR_Question__c.sObjectType.getDescribe(), 'Update') &&
                               ATR_FLSCheck.checkObjectSecurity(ATR_Question__c.sObjectType.getDescribe(), 'Create') &&
                               ATR_FLSCheck.checkObjectSecurity(ATR_Choice__c.sObjectType.getDescribe(), 'Update') &&
                               ATR_FLSCheck.checkObjectSecurity(ATR_Choice__c.sObjectType.getDescribe(), 'Create') &&
                               ATR_FLSCheck.checkObjectSecurity(ATR_Choice__c.sObjectType.getDescribe(), 'Delete');
        
        if (isUpsertable) {
            upsert question;
            for (ATR_Choice__c choice : answers) {
                if (choice.Id == null) {
                    choice.ATR_Question__c = question.Id;
                }
            }
                                                               
            // Copying choices to another list
            // to avoid error (cannot upsert on List<sObject>)
            List<ATR_Choice__c> choiceList = new List<ATR_Choice__c>();
            choiceList.addAll(answers);
            upsert choiceList;
            delete todelete;
        }                                             
        return getTemplateQuestions(templateId);
    }
    
    @AuraEnabled
    public static void removeQuestion(String questionId) {
        Boolean isDeleteable = ATR_FLSCheck.checkObjectSecurity(ATR_Question__c.sObjectType.getDescribe(), 'Delete');
        if (isDeleteable) {
            List<ATR_Question__c> questions = [ SELECT Id FROM ATR_Question__c WHERE Id = :questionId ];
            delete questions;
        }
    }

    @AuraEnabled
    public static List<ATR_Question__c> updateQuestionOrder(List<ATR_Question__c> questions) {
        List<string> fields = new List<string> { 
            'Question__c',
            'Order_Number__c'
        };
        
        boolean isUpdatable = ATR_FLSCheck.checkFLS(ATR_Question__c.sObjectType.getDescribe(), fields, 'Update');
        if (isUpdatable) {
        	update questions;
        }
        return questions;
    }

    @AuraEnabled
    public static List<ATR_Choice__c> getAnswers(String questionId) {
        List<ATR_Choice__c> choices = new List<ATR_Choice__c>();
        
        List<string> fields = new List<string> { 
            'Id', 
            'Answer__c',
            'Score__c',
            'Order_Number__c'
        };
        
        boolean isAccessible = ATR_FLSCheck.checkFLS(ATR_Choice__c.sObjectType.getDescribe(), fields, 'Read');
        if (isAccessible) {
            choices = [ SELECT Id, Answer__c, Score__c, Order_Number__c 
                        FROM ATR_Choice__c 
                        WHERE ATR_Question__c =: questionId
                        ORDER BY Order_Number__c ];
        }
        return choices;
    }
}