force-app/main/default/objects/ATR_Taken__c/ATR_Taken__c.object-meta.xml
<CustomObject>
    <label>ATR Taken</label>
    <nameField>
        <displayFormat>ATR-{00000}</displayFormat>
        <label>ATR Completed No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ATRs Taken</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ATR_Taken__c/fields/ATR_Template__c.field-meta.xml
<CustomField>
    <fullName>ATR_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ATR Template</label>
    <referenceTo>ATR_Template__c</referenceTo>
    <relationshipLabel>ATRs Taken</relationshipLabel>
    <relationshipName>ATRs_Taken</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ATR_Taken__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Risk Profile History</relationshipLabel>
    <relationshipName>ATRs_Taken</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ATR_Taken__c/fields/Risk_Profile__c.field-meta.xml
<CustomField>
    <fullName>Risk_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Risk Profile</label>
    <referenceTo>Risk_Profile__c</referenceTo>
    <relationshipLabel>Client ATR Questionnaires</relationshipLabel>
    <relationshipName>ATRs_Taken</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ATR_Template__c/ATR_Template__c.object-meta.xml
<CustomObject>
    <label>ATR Template</label>
    <nameField>
        <label>ATR Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ATR Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Risk_Profile__c/Risk_Profile__c.object-meta.xml
<CustomObject>
    <label>Risk Profile</label>
    <nameField>
        <label>Risk Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Risk_Profile__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>This is the description text that will display on the summary page after a questionnaire has been taken.</inlineHelpText>
    <label>Description</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Risk_Profile__c/fields/HighScore__c.field-meta.xml
<CustomField>
    <fullName>HighScore__c</fullName>
    <inlineHelpText>If the total score for a client falls between the Low and High Bands for a &apos;Risk Profile&apos; that profile will be selected.  Scores should not overlap, i.e. If the previous profile has a &apos;High Band&apos; of 10, the &apos;Low Band&apos; of this profile should start at 11.</inlineHelpText>
    <label>High Band</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Risk_Profile__c/fields/LowScore__c.field-meta.xml
<CustomField>
    <fullName>LowScore__c</fullName>
    <inlineHelpText>If the total score for a client falls between the Low and High Bands for a &apos;Risk Profile&apos; that profile will be selected.  Scores should not overlap, i.e. If the previous profile has a &apos;High Band&apos; of 10, the &apos;Low Band&apos; of this profile should start at 11.</inlineHelpText>
    <label>Low Band</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ATR_ClientControllerTest.cls
@isTest
public class ATR_ClientControllerTest {
    
    @isTest
    static void getClientTest() {
        Account client = new Account(Name = 'Answer Foster');
        insert client;
        
        Account actual = ATR_ClientController.getClient(client.Id);
        System.assert(actual != null);
        System.assertEquals(client.Name, actual.Name);
        System.assertEquals(client.Id, actual.Id);
    }
    
    @isTest
    static void getTemplatesTest() {
        List<ATR_Template__c> templates = new List<ATR_Template__c>();
        Integer numTemplates = 5;
        
        for (Integer i = 0; i < numTemplates; i++) {
            templates.add(new ATR_Template__c(Name = 'Template ' + i));
        }
        insert templates;
        
        List<ATR_Template__c> actual = ATR_ClientController.getTemplates();
        System.assertEquals(numTemplates, actual.size());
        for (Integer i = 0; i < numTemplates; i++) {
            System.assertEquals('Template ' + i, actual[i].Name);
        }
        
    }
    
    @isTest
    static void getRiskProfileTest() {
        List<Risk_Profile__c> riskProfiles = new List<Risk_Profile__c>();
        riskProfiles.add(new Risk_Profile__c( Name = 'Low',    LowScore__c = 0,  HighScore__c = 5,  Description__c = 'Low Risk'));
        riskProfiles.add(new Risk_Profile__c( Name = 'Medium', LowScore__c = 6,  HighScore__c = 10, Description__c = 'Medium Risk'));
        riskProfiles.add(new Risk_Profile__c( Name = 'High',   LowScore__c = 11, HighScore__c = 15, Description__c = 'High Risk'));
        insert riskProfiles;
        
        Risk_Profile__c actual = ATR_ClientController.getRiskProfile('3');
        System.assertEquals('Low', actual.Name);
        actual = ATR_ClientController.getRiskProfile('7');
        System.assertEquals('Medium', actual.Name);
        actual = ATR_ClientController.getRiskProfile('12');
        System.assertEquals('High', actual.Name);
        actual = ATR_ClientController.getRiskProfile('17');
        System.assertEquals(null, actual);
    }
    
    @isTest
    static void updateATRTest() {
        Risk_Profile__c profile = new Risk_Profile__c( Name = 'Low', LowScore__c = 0, HighScore__c = 5, Description__c = 'Low Risk');
        ATR_Taken__c actual = ATR_ClientController.updateATR(null, profile.Id);
        System.assertEquals(null, actual);
        
        // Set up test data
        Account client = new Account( Name = 'Andrew Foster' );
        insert client;
        
        ATR_Template__c template = new ATR_Template__c( Name = 'TestTemplate' );
        insert template;
        
        ATR_Taken__c atr = new ATR_Taken__c(ATR_Template__c = template.Id, Client__c = client.Id);
        insert atr;
        actual = ATR_ClientController.updateATR(atr, profile.Id);
        System.assert(actual != null);
        System.assertEquals(profile.Id, actual.Risk_Profile__c);
    }
}