force-app/main/default/objects/ATR_Taken__c/ATR_Taken__c.object-meta.xml
<CustomObject>
    <label>ATR Taken</label>
    <nameField>
        <displayFormat>ATR-{00000}</displayFormat>
        <label>ATR Completed No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ATRs Taken</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ATR_Taken__c/fields/ATR_Template__c.field-meta.xml
<CustomField>
    <fullName>ATR_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ATR Template</label>
    <referenceTo>ATR_Template__c</referenceTo>
    <relationshipLabel>ATRs Taken</relationshipLabel>
    <relationshipName>ATRs_Taken</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ATR_Taken__c/fields/Risk_Profile__c.field-meta.xml
<CustomField>
    <fullName>Risk_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Risk Profile</label>
    <referenceTo>Risk_Profile__c</referenceTo>
    <relationshipLabel>Client ATR Questionnaires</relationshipLabel>
    <relationshipName>ATRs_Taken</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ATR_Template__c/ATR_Template__c.object-meta.xml
<CustomObject>
    <label>ATR Template</label>
    <nameField>
        <label>ATR Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ATR Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Risk_Profile__c/Risk_Profile__c.object-meta.xml
<CustomObject>
    <label>Risk Profile</label>
    <nameField>
        <label>Risk Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risk Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Risk_Profile__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>This is the description text that will display on the summary page after a questionnaire has been taken.</inlineHelpText>
    <label>Description</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Risk_Profile__c/fields/HighScore__c.field-meta.xml
<CustomField>
    <fullName>HighScore__c</fullName>
    <inlineHelpText>If the total score for a client falls between the Low and High Bands for a &apos;Risk Profile&apos; that profile will be selected.  Scores should not overlap, i.e. If the previous profile has a &apos;High Band&apos; of 10, the &apos;Low Band&apos; of this profile should start at 11.</inlineHelpText>
    <label>High Band</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Risk_Profile__c/fields/LowScore__c.field-meta.xml
<CustomField>
    <fullName>LowScore__c</fullName>
    <inlineHelpText>If the total score for a client falls between the Low and High Bands for a &apos;Risk Profile&apos; that profile will be selected.  Scores should not overlap, i.e. If the previous profile has a &apos;High Band&apos; of 10, the &apos;Low Band&apos; of this profile should start at 11.</inlineHelpText>
    <label>Low Band</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ATR_ClientController.cls
public with sharing class ATR_ClientController {
    @AuraEnabled
    public static Account getClient(String clientId) {
        Account acct;
        List<string> fields = new List<string> { 'Id', 'Name' };
        
        boolean isAccessible = ATR_FLSCheck.checkFLS(Account.sObjectType.getDescribe(), fields, 'Read');
        if (isAccessible) {
            acct = [ SELECT Id, Name FROM Account WHERE Id = :clientId ];
        }
        return acct;
    }

    @AuraEnabled
    public static List<ATR_Template__c> getTemplates() {
        List<ATR_Template__c> templates = new List<ATR_Template__c>();
        List<string> fields = new List<string> { 'Id', 'Name' };
        
        boolean isAccessible = ATR_FLSCheck.checkFLS(ATR_Template__c.sObjectType.getDescribe(), fields, 'Read');
        if (isAccessible) {
            templates = [ SELECT Id, Name FROM ATR_Template__c ORDER BY Name ];
        }
        return templates;
    }

	@AuraEnabled
    public static Risk_Profile__c getRiskProfile(String score) {
        List<string> fields = new List<string> { 
            'Id', 
            'Name',
            'LowScore__c', 
            'HighScore__c', 
            'Description__c'
        };
        
        boolean isAccessible = ATR_FLSCheck.checkFLS(Risk_Profile__c.sObjectType.getDescribe(), fields, 'Read');
        if (isAccessible) {
            List<Risk_Profile__c> riskProfiles = [ SELECT Id, Name, LowScore__c, HighScore__c, Description__c
                                                            FROM Risk_Profile__c ];
    
            for(Risk_Profile__c riskProfile : riskProfiles) {
                Decimal low  = riskProfile.lowScore__c;
                Decimal high = riskProfile.highScore__c;
                Decimal totalScore = Decimal.valueOf(score);
    
                if (totalScore >= low && totalScore <= high) {
                    return riskProfile;
                }
            }
        }
        return null;
    }
    
    @auraEnabled
    public static ATR_Taken__c updateATR(ATR_Taken__c atr, String riskProfileId) {        
        // ATR should have been created in this stage
        if (atr != null) {
            Boolean isUpdateable = ATR_FLSCheck.checkObjectSecurity(ATR_Taken__c.sObjectType.getDescribe(), 'Update');
            if (isUpdateable) {
                atr.Risk_Profile__c = riskProfileId;
            	update atr;
            }
            return atr;
        }
        return null;
    }
}